// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedForm from "stimulus-rails-nested-form"
application.register("nested-form", NestedForm)

import DescriptionController from "./description_controller"
application.register("description", DescriptionController)

import TaskController from "./task_controller"
application.register("task", TaskController)

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

